# Generated by Django 5.2.17 on 2026-09-16 00:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, unique=True, verbose_name='Nome')),
                ('active', models.BooleanField(default=True, verbose_name='Ativo')),
            ],
            options={
                'ordering': ['name'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ProductCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, unique=True, verbose_name='Nome')),
                ('active', models.BooleanField(default=True, verbose_name='Ativo')),
            ],
            options={
                'ordering': ['name'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sku', models.CharField(max_length=60, unique=True, verbose_name='SKU')),
                ('name', models.CharField(db_index=True, max_length=240, verbose_name='Produto')),
                ('unit', models.CharField(default='UN', max_length=12, verbose_name='Unidade')),
                ('kind', models.CharField(choices=[('SIMPLE', 'Produto'), ('KIT', 'Kit virtual')], default='SIMPLE', max_length=10, verbose_name='Tipo')),
                ('minimum', models.DecimalField(decimal_places=4, default=0, max_digits=18, verbose_name='Estoque mínimo')),
                ('active', models.BooleanField(default=True, verbose_name='Ativo')),
                ('quantity', models.DecimalField(decimal_places=4, default=0, editable=False, max_digits=18)),
                ('value', models.DecimalField(decimal_places=6, default=0, editable=False, max_digits=24)),
                ('average_cost', models.DecimalField(decimal_places=6, default=0, editable=False, max_digits=24)),
                ('brand', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='products.brand', verbose_name='Marca')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='products.productcategory', verbose_name='Categoria')),
            ],
            options={
                'ordering': ['name', 'pk'],
            },
        ),
        migrations.CreateModel(
            name='ProductComposition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=4, max_digits=18, verbose_name='Quantidade')),
                ('component', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='used_in', to='products.product')),
                ('kit', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='components', to='products.product')),
            ],
        ),
        migrations.AddConstraint(
            model_name='product',
            constraint=models.CheckConstraint(condition=models.Q(('average_cost__gte', 0), ('minimum__gte', 0), ('quantity__gte', 0), ('value__gte', 0)), name='product_nonnegative'),
        ),
        migrations.AddConstraint(
            model_name='productcomposition',
            constraint=models.UniqueConstraint(fields=('kit', 'component'), name='unique_component'),
        ),
        migrations.AddConstraint(
            model_name='productcomposition',
            constraint=models.CheckConstraint(condition=models.Q(('quantity__gt', 0), models.Q(('kit', models.F('component')), _negated=True)), name='valid_component'),
        ),
    ]
