# Generated by Django 5.2.17 on 2026-10-07 22:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='product',
            name='product_nonnegative',
        ),
        migrations.AddConstraint(
            model_name='product',
            constraint=models.CheckConstraint(condition=models.Q(('average_cost__gte', 0), ('minimum__gte', 0)), name='product_cost_minimum_nonnegative'),
        ),
    ]
