# Generated by Django 5.2.17 on 2026-09-16 10:02

import django.core.validators
import django.db.models.deletion
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('inventory', '0004_alter_stockoperation_kind'),
        ('products', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SalesChannel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, unique=True, verbose_name='Nome')),
                ('active', models.BooleanField(default=True, verbose_name='Ativo')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Sale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('creation_fingerprint', models.CharField(editable=False, max_length=64)),
                ('revision', models.PositiveIntegerField(default=0, editable=False)),
                ('date', models.DateField(db_index=True, verbose_name='Data da venda')),
                ('invoice_number', models.CharField(max_length=40, verbose_name='Número da NF')),
                ('invoice_series', models.CharField(blank=True, default='', max_length=20, verbose_name='Série')),
                ('products_amount', models.DecimalField(decimal_places=2, default=0, max_digits=18, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Valor dos produtos (R$)')),
                ('discount', models.DecimalField(decimal_places=2, default=0, max_digits=18, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Desconto (R$)')),
                ('shipping_received', models.DecimalField(decimal_places=2, default=0, max_digits=18, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Frete recebido (R$)')),
                ('shipping_paid', models.DecimalField(decimal_places=2, default=0, max_digits=18, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Frete pago (R$)')),
                ('fees', models.DecimalField(decimal_places=2, default=0, max_digits=18, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Taxas (R$)')),
                ('difal', models.DecimalField(decimal_places=2, default=0, max_digits=18, validators=[django.core.validators.MinValueValidator(0)], verbose_name='DIFAL (R$)')),
                ('commission', models.DecimalField(decimal_places=2, default=0, max_digits=18, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Comissão (R$)')),
                ('other_costs', models.DecimalField(decimal_places=2, default=0, max_digits=18, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Outros custos variáveis (R$)')),
                ('tax_override', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Imposto manual (R$)')),
                ('tax_reason', models.CharField(blank=True, max_length=500, verbose_name='Motivo do imposto manual')),
                ('notes', models.TextField(blank=True, max_length=3000, verbose_name='Observação')),
                ('status', models.CharField(choices=[('DRAFT', 'Rascunho'), ('CONFIRMED', 'Confirmada'), ('CANCELLED', 'Cancelada')], db_index=True, default='DRAFT', max_length=12)),
                ('tax_snapshot', models.JSONField(default=dict, editable=False)),
                ('tax_amount', models.DecimalField(decimal_places=2, default=0, max_digits=18, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Imposto aplicado')),
                ('cmv', models.DecimalField(decimal_places=6, default=0, editable=False, max_digits=24)),
                ('minimum_margin', models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=6)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('confirmed_at', models.DateTimeField(editable=False, null=True)),
                ('cancelled_at', models.DateTimeField(editable=False, null=True)),
                ('cancellation_reason', models.CharField(blank=True, max_length=500)),
                ('external_id', models.CharField(blank=True, max_length=120)),
                ('source', models.CharField(default='manual', max_length=40)),
                ('cancelled_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='cancelled_sales', to=settings.AUTH_USER_MODEL)),
                ('confirmed_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='confirmed_sales', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_sales', to=settings.AUTH_USER_MODEL)),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inventory.stocklocation', verbose_name='Local de estoque')),
                ('return_operation', models.OneToOneField(editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='sale_cancellation', to='inventory.stockoperation')),
                ('stock_operation', models.OneToOneField(editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='sale_confirmation', to='inventory.stockoperation')),
                ('channel', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='sales.saleschannel', verbose_name='Canal')),
            ],
            options={
                'ordering': ['-date', '-pk'],
            },
        ),
        migrations.CreateModel(
            name='SaleItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=4, max_digits=18, validators=[django.core.validators.MinValueValidator(Decimal('0.0001'))])),
                ('sku_snapshot', models.CharField(blank=True, max_length=60)),
                ('name_snapshot', models.CharField(blank=True, max_length=200)),
                ('unit_cost', models.DecimalField(decimal_places=6, default=0, max_digits=24)),
                ('cmv', models.DecimalField(decimal_places=6, default=0, max_digits=24)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='products.product')),
                ('sale', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='items', to='sales.sale')),
            ],
            options={
                'ordering': ['pk'],
            },
        ),
        migrations.CreateModel(
            name='SaleConsumption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('movement', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='inventory.stockmovement')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='consumptions', to='sales.saleitem')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='TaxRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, verbose_name='Nome')),
                ('rate', models.DecimalField(decimal_places=4, max_digits=7, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Alíquota (%)')),
                ('starts_on', models.DateField(verbose_name='Início da vigência')),
                ('ends_on', models.DateField(blank=True, null=True, verbose_name='Fim da vigência')),
                ('base', models.CharField(choices=[('REVENUE', 'Produtos − desconto + frete recebido'), ('PRODUCTS', 'Produtos − desconto')], max_length=20, verbose_name='Base de cálculo')),
                ('active', models.BooleanField(default=True, verbose_name='Ativa')),
            ],
            options={
                'ordering': ['name', '-starts_on'],
                'constraints': [models.CheckConstraint(condition=models.Q(('rate__gte', 0), ('rate__lte', 100)), name='sales_tax_rate_range'), models.CheckConstraint(condition=models.Q(('ends_on__isnull', True), ('ends_on__gte', models.F('starts_on')), _connector='OR'), name='sales_tax_dates')],
            },
        ),
        migrations.AddField(
            model_name='sale',
            name='tax_rule',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='sales.taxrule', verbose_name='Regra tributária'),
        ),
        migrations.AddConstraint(
            model_name='saleitem',
            constraint=models.CheckConstraint(condition=models.Q(('quantity__gt', 0)), name='sales_positive_quantity'),
        ),
        migrations.AddIndex(
            model_name='sale',
            index=models.Index(fields=['channel', 'date'], name='sales_sale_channel_6db1bb_idx'),
        ),
        migrations.AddConstraint(
            model_name='sale',
            constraint=models.UniqueConstraint(fields=('invoice_number', 'invoice_series'), name='sales_unique_invoice'),
        ),
        migrations.AddConstraint(
            model_name='sale',
            constraint=models.CheckConstraint(condition=models.Q(('discount__lte', models.F('products_amount'))), name='sales_valid_discount'),
        ),
    ]
