# Generated by Django 5.2.17 on 2026-09-16 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0002_protect_history'),
    ]

    operations = [
        migrations.AlterField(
            model_name='saleitem',
            name='name_snapshot',
            field=models.CharField(blank=True, max_length=240),
        ),
    ]
