# Generated by Django 5.2.17 on 2026-09-16 14:46

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0003_alter_saleitem_name_snapshot'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='sale',
            name='extra_costs_total',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=18, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Total de taxas extras'),
        ),
        migrations.CreateModel(
            name='TaxRateChange',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('effective_from', models.DateField(verbose_name='Usar a partir de')),
                ('rate', models.DecimalField(decimal_places=4, max_digits=7, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Nova alíquota (%)')),
                ('base', models.CharField(choices=[('REVENUE', 'Produtos − desconto + frete recebido'), ('PRODUCTS', 'Produtos − desconto')], max_length=20, verbose_name='Base de cálculo')),
                ('reason', models.CharField(max_length=500, verbose_name='Motivo')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('rule', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='changes', to='sales.taxrule')),
            ],
            options={
                'ordering': ['-effective_from', '-pk'],
            },
        ),
        migrations.CreateModel(
            name='SaleTaxRevision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('before_amount', models.DecimalField(decimal_places=2, default=0, max_digits=18, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Imposto anterior')),
                ('after_amount', models.DecimalField(decimal_places=2, default=0, max_digits=18, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Imposto recalculado')),
                ('before_snapshot', models.JSONField()),
                ('after_snapshot', models.JSONField()),
                ('sale', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tax_revisions', to='sales.sale')),
                ('change', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='revisions', to='sales.taxratechange')),
            ],
        ),
        migrations.CreateModel(
            name='SaleExtraCost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, verbose_name='Taxa / descrição')),
                ('amount', models.DecimalField(decimal_places=2, default=0, max_digits=18, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Valor (R$)')),
                ('sale', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='extra_costs', to='sales.sale')),
            ],
            options={
                'ordering': ['pk'],
                'constraints': [models.CheckConstraint(condition=models.Q(('amount__gte', 0)), name='sales_extra_nonnegative')],
            },
        ),
        migrations.AddIndex(
            model_name='taxratechange',
            index=models.Index(fields=['rule', 'effective_from'], name='sales_taxra_rule_id_9adc94_idx'),
        ),
        migrations.AddConstraint(
            model_name='taxratechange',
            constraint=models.CheckConstraint(condition=models.Q(('rate__gte', 0), ('rate__lte', 100)), name='sales_changed_tax_rate_range'),
        ),
        migrations.AddConstraint(
            model_name='saletaxrevision',
            constraint=models.UniqueConstraint(fields=('sale', 'change'), name='sales_unique_tax_revision'),
        ),
    ]
