# Generated by Django 5.2.17 on 2026-09-18 18:01

import django.db.models.deletion
import django.db.models.expressions
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0005_alter_stockoperation_kind'),
        ('sales', '0005_audited_tax_recalculation'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='sale',
            name='sales_unique_invoice',
        ),
        migrations.AddField(
            model_name='sale',
            name='revenue_adjustment',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=18, verbose_name='Ajuste gerencial da receita (R$)'),
        ),
        migrations.AddField(
            model_name='sale',
            name='revenue_adjustment_reason',
            field=models.CharField(blank=True, max_length=500, verbose_name='Motivo do ajuste de receita'),
        ),
        migrations.AlterField(
            model_name='sale',
            name='channel',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='sales.saleschannel', verbose_name='Canal'),
        ),
        migrations.AlterField(
            model_name='sale',
            name='date',
            field=models.DateField(db_index=True, default=django.utils.timezone.localdate, verbose_name='Data da venda'),
        ),
        migrations.AlterField(
            model_name='sale',
            name='invoice_number',
            field=models.CharField(blank=True, default='', max_length=40, verbose_name='Número da NF'),
        ),
        migrations.AlterField(
            model_name='sale',
            name='location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='inventory.stocklocation', verbose_name='Local de estoque'),
        ),
        migrations.AddConstraint(
            model_name='sale',
            constraint=models.UniqueConstraint(condition=models.Q(('invoice_number', ''), _negated=True), fields=('invoice_number', 'invoice_series'), name='sales_unique_invoice'),
        ),
        migrations.AddConstraint(
            model_name='sale',
            constraint=models.CheckConstraint(condition=models.Q(('products_amount__gte', django.db.models.expressions.CombinedExpression(django.db.models.expressions.CombinedExpression(models.F('discount'), '-', models.F('shipping_received')), '-', models.F('revenue_adjustment')))), name='sales_nonnegative_revenue'),
        ),
        migrations.AddConstraint(
            model_name='sale',
            constraint=models.CheckConstraint(condition=models.Q(('status', 'DRAFT'), ('status', 'CANCELLED'), models.Q(('channel__isnull', False), ('location__isnull', False)), _connector='OR'), name='sales_confirmed_context'),
        ),
    ]
