# Generated by Django 5.2.17 on 2026-09-18 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0006_remove_sale_sales_unique_invoice_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taxratechange',
            name='base',
            field=models.CharField(choices=[('REVENUE', 'Receita operacional, incluindo ajuste gerencial'), ('PRODUCTS', 'Produtos − desconto')], max_length=20, verbose_name='Base de cálculo'),
        ),
        migrations.AlterField(
            model_name='taxrule',
            name='base',
            field=models.CharField(choices=[('REVENUE', 'Receita operacional, incluindo ajuste gerencial'), ('PRODUCTS', 'Produtos − desconto')], max_length=20, verbose_name='Base de cálculo'),
        ),
    ]
