# Generated by Django 5.2.17 on 2026-10-07 18:38

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0007_remove_unused_duplicate_full'),
        ('sales', '0007_alter_taxratechange_base_alter_taxrule_base'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SaleRecovery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.UUIDField(default=uuid.uuid4, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('reason', models.CharField(max_length=500)),
                ('before_revision', models.PositiveIntegerField()),
                ('before_fees', models.DecimalField(decimal_places=2, default=0, max_digits=18, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Taxas anteriores')),
                ('after_fees', models.DecimalField(decimal_places=2, default=0, max_digits=18, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Taxas corrigidas')),
                ('cancellation_snapshot', models.JSONField()),
                ('actor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('original_operation', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='inventory.stockoperation')),
                ('recovery_operation', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='inventory.stockoperation')),
                ('returned_operation', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='inventory.stockoperation')),
                ('sale', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='recoveries', to='sales.sale')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('sale', 'before_revision'), name='sales_unique_recovery_revision')],
            },
        ),
    ]
