# Generated by Django 5.2.17 on 2026-10-10 12:12

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('sales', '0012_protect_sale_context_correction'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Command',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.UUIDField(default=uuid.uuid4, unique=True)),
                ('fingerprint', models.CharField(max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('kind', models.CharField(max_length=24)),
                ('reason', models.CharField(max_length=500)),
                ('before', models.JSONField(default=dict)),
                ('after', models.JSONField(default=dict)),
                ('actor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CommissionPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer', models.CharField(blank=True, max_length=240, verbose_name='Cliente')),
                ('rate', models.DecimalField(decimal_places=4, max_digits=7, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Percentual (%)')),
                ('rate_source', models.CharField(choices=[('MANUAL', 'Manual na venda'), ('PAYEE', 'Padrão do comissionado'), ('DEFAULT', 'Padrão global')], max_length=20)),
                ('base', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('total', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('override_total', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True)),
                ('cancelled', models.BooleanField(default=False)),
                ('revision', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('sale', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='commission_plan', to='sales.sale')),
            ],
        ),
        migrations.CreateModel(
            name='CommissionSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('default_rate', models.DecimalField(decimal_places=4, default=0, max_digits=7, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Percentual (%)')),
            ],
            options={
                'constraints': [models.CheckConstraint(condition=models.Q(('id', 1)), name='commission_single_settings'), models.CheckConstraint(condition=models.Q(('default_rate__gte', 0), ('default_rate__lte', 100)), name='commission_default_rate')],
            },
        ),
        migrations.CreateModel(
            name='Installment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.PositiveIntegerField()),
                ('due_date', models.DateField()),
                ('amount', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('forecast', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='installments', to='commissions.commissionplan')),
            ],
            options={
                'ordering': ['number', 'pk'],
            },
        ),
        migrations.CreateModel(
            name='Entry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(db_index=True)),
                ('received', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('released', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('command', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='entries', to='commissions.command')),
                ('reversal_of', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='reversal', to='commissions.entry')),
                ('installment', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='entries', to='commissions.installment')),
            ],
            options={
                'ordering': ['date', 'pk'],
            },
        ),
        migrations.CreateModel(
            name='Payee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=180, verbose_name='Nome')),
                ('kind', models.CharField(choices=[('EMPLOYEE', 'Vendedor interno'), ('REP', 'Representante'), ('PARTNER', 'Parceiro comercial'), ('OTHER', 'Outro')], default='EMPLOYEE', max_length=20, verbose_name='Tipo')),
                ('default_rate', models.DecimalField(blank=True, decimal_places=4, max_digits=7, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Percentual (%)')),
                ('active', models.BooleanField(default=True, verbose_name='Ativo')),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Usuário para consulta (opcional)')),
            ],
            options={
                'ordering': ['name', 'pk'],
            },
        ),
        migrations.AddField(
            model_name='commissionplan',
            name='payee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='plans', to='commissions.payee'),
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(db_index=True)),
                ('period', models.DateField()),
                ('amount', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('method', models.CharField(max_length=100, verbose_name='Forma de pagamento')),
                ('command', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='payment', to='commissions.command')),
                ('payee', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payments', to='commissions.payee')),
                ('reversal_of', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='reversal', to='commissions.payment')),
            ],
            options={
                'ordering': ['-date', '-pk'],
            },
        ),
        migrations.CreateModel(
            name='Allocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('entry', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='allocations', to='commissions.entry')),
                ('payment', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='allocations', to='commissions.payment')),
            ],
        ),
        migrations.AddConstraint(
            model_name='installment',
            constraint=models.UniqueConstraint(fields=('plan', 'number'), name='commission_installment_number'),
        ),
        migrations.AddConstraint(
            model_name='installment',
            constraint=models.CheckConstraint(condition=models.Q(('amount__gt', 0), ('forecast__gte', 0)), name='commission_installment_values'),
        ),
        migrations.AddConstraint(
            model_name='payee',
            constraint=models.CheckConstraint(condition=models.Q(('default_rate__isnull', True), models.Q(('default_rate__gte', 0), ('default_rate__lte', 100)), _connector='OR'), name='commission_payee_rate'),
        ),
        migrations.AddConstraint(
            model_name='commissionplan',
            constraint=models.CheckConstraint(condition=models.Q(('base__gte', 0), ('rate__gte', 0), ('rate__lte', 100), ('total__gte', 0)), name='commission_plan_values'),
        ),
        migrations.AddConstraint(
            model_name='allocation',
            constraint=models.UniqueConstraint(fields=('payment', 'entry'), name='commission_payment_entry'),
        ),
    ]
