# Generated by Django 5.2.17 on 2026-10-10 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commissions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='entry',
            name='terms',
            field=models.JSONField(default=dict),
        ),
    ]
