# Generated by Django 5.2.17 on 2026-10-10 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commissions', '0003_immutable_ledger'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='allocation',
            constraint=models.CheckConstraint(condition=models.Q(('amount', 0), _negated=True), name='commission_allocation_nonzero'),
        ),
        migrations.AddConstraint(
            model_name='entry',
            constraint=models.CheckConstraint(condition=models.Q(('received', 0), ('released', 0), _negated=True), name='commission_entry_nonzero'),
        ),
        migrations.AddConstraint(
            model_name='payment',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('amount__gt', 0), ('reversal_of__isnull', True)), models.Q(('amount__lt', 0), ('reversal_of__isnull', False)), _connector='OR'), name='commission_payment_sign'),
        ),
    ]
