# Generated by Django 5.2.17 on 2026-09-18 14:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0001_initial'),
        ('sales', '0005_audited_tax_recalculation'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BlingConnection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('issuer', models.CharField(max_length=14, unique=True)),
                ('tokens', models.TextField(blank=True, editable=False)),
                ('expires_at', models.DateTimeField(editable=False, null=True)),
                ('last_request_at', models.DateTimeField(editable=False, null=True)),
                ('last_sync_at', models.DateTimeField(editable=False, null=True)),
            ],
            options={
                'constraints': [models.CheckConstraint(condition=models.Q(('id', 1)), name='single_bling_connection')],
            },
        ),
        migrations.CreateModel(
            name='ImportRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start', models.DateField()),
                ('end', models.DateField()),
                ('page', models.PositiveIntegerField()),
                ('source_status', models.PositiveIntegerField(default=5)),
                ('processed', models.PositiveIntegerField(default=0)),
                ('errors', models.PositiveIntegerField(default=0)),
                ('has_more', models.BooleanField(default=False)),
                ('message', models.CharField(blank=True, max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('finished_at', models.DateTimeField(null=True)),
                ('actor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('connection', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='integrations.blingconnection')),
            ],
            options={
                'ordering': ['-pk'],
            },
        ),
        migrations.CreateModel(
            name='InvoiceImport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external_id', models.CharField(max_length=40)),
                ('access_key', models.CharField(blank=True, max_length=44)),
                ('number', models.CharField(max_length=30)),
                ('series', models.CharField(blank=True, max_length=10)),
                ('issued_on', models.DateField(null=True)),
                ('source_status', models.CharField(blank=True, max_length=20)),
                ('source', models.JSONField(default=dict)),
                ('fingerprint', models.CharField(max_length=64)),
                ('revision', models.PositiveIntegerField(default=1)),
                ('status', models.CharField(choices=[('PENDING', 'Pendente'), ('IMPORTED', 'Importada'), ('IGNORED', 'Ignorada'), ('ERROR', 'Com erro')], default='PENDING', max_length=12)),
                ('error', models.CharField(blank=True, max_length=500)),
                ('discrepancy', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('checked_at', models.DateTimeField(auto_now=True)),
                ('connection', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='integrations.blingconnection')),
                ('sale', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='bling_import', to='sales.sale')),
            ],
            options={
                'ordering': ['-issued_on', '-pk'],
                'indexes': [models.Index(fields=['status', 'issued_on'], name='integration_status_b825b5_idx')],
                'constraints': [models.UniqueConstraint(fields=('connection', 'external_id'), name='bling_unique_invoice'), models.UniqueConstraint(condition=models.Q(('access_key', ''), _negated=True), fields=('access_key',), name='bling_unique_key')],
            },
        ),
        migrations.CreateModel(
            name='ProductAlias',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=120)),
                ('unit', models.CharField(max_length=12)),
                ('connection', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='integrations.blingconnection')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='products.product')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('connection', 'code', 'unit'), name='bling_unique_alias')],
            },
        ),
    ]
