# Generated by Django 5.2.17 on 2026-09-18 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('integrations', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoiceimport',
            name='approved_source',
            field=models.JSONField(default=dict, editable=False),
        ),
    ]
