# Generated by Django 5.2.17 on 2026-09-18 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('integrations', '0002_invoiceimport_approved_source'),
        ('sales', '0005_audited_tax_recalculation'),
    ]

    operations = [
        migrations.AddField(
            model_name='importrun',
            name='error_ids',
            field=models.JSONField(default=list),
        ),
        migrations.AddConstraint(
            model_name='invoiceimport',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('sale__isnull', False), ('status', 'IMPORTED')), models.Q(models.Q(('status', 'IMPORTED'), _negated=True), ('sale__isnull', True)), _connector='OR'), name='bling_sale_status_consistent'),
        ),
    ]
