# Generated by Django 5.2.17 on 2026-09-25 18:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('integrations', '0004_protect_import_identity'),
        ('inventory', '0007_remove_unused_duplicate_full'),
        ('sales', '0007_alter_taxratechange_base_alter_taxrule_base'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReviewDefaults',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_store', models.CharField(max_length=40, verbose_name='Loja externa Full')),
                ('default_channel', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='sales.saleschannel', verbose_name='Canal Mercadovet / demais lojas')),
                ('default_location', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='inventory.stocklocation', verbose_name='Estoque Mercadovet / demais lojas')),
                ('full_channel', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='sales.saleschannel', verbose_name='Canal Full')),
                ('full_location', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='inventory.stocklocation', verbose_name='Estoque Full')),
            ],
            options={
                'constraints': [models.CheckConstraint(condition=models.Q(('id', 1)), name='single_bling_review_defaults')],
            },
        ),
    ]
