# Generated by Django 5.2.17 on 2026-09-28 20:30

import django.db.models.deletion
from django.db import migrations, models


def install(apps, schema_editor):
    if schema_editor.connection.vendor != 'postgresql': return
    schema_editor.execute("""CREATE FUNCTION mvet_protect_bling_purchase() RETURNS trigger AS $$
    BEGIN
      IF TG_OP = 'DELETE' THEN RAISE EXCEPTION 'Imported purchase references cannot be deleted'; END IF;
      IF NEW.connection_id <> OLD.connection_id OR NEW.external_id <> OLD.external_id OR NEW.access_key <> OLD.access_key THEN
        RAISE EXCEPTION 'External purchase identity is immutable';
      END IF;
      IF OLD.purchase_id IS NOT NULL AND (NEW.purchase_id IS DISTINCT FROM OLD.purchase_id OR NEW.approved_source IS DISTINCT FROM OLD.approved_source) THEN
        RAISE EXCEPTION 'Imported purchase linkage and snapshot are immutable';
      END IF;
      RETURN NEW;
    END; $$ LANGUAGE plpgsql""")
    schema_editor.execute('CREATE TRIGGER protect_bling_purchase BEFORE UPDATE OR DELETE ON integrations_purchaseinvoiceimport FOR EACH ROW EXECUTE FUNCTION mvet_protect_bling_purchase()')


def uninstall(apps, schema_editor):
    if schema_editor.connection.vendor != 'postgresql': return
    schema_editor.execute('DROP TRIGGER protect_bling_purchase ON integrations_purchaseinvoiceimport')
    schema_editor.execute('DROP FUNCTION mvet_protect_bling_purchase()')


class Migration(migrations.Migration):

    dependencies = [
        ('integrations', '0005_reviewdefaults'),
        ('purchases', '0002_protect_purchase_history'),
    ]

    operations = [
        migrations.AddField(
            model_name='importrun',
            name='kind',
            field=models.CharField(choices=[('SALE', 'Vendas'), ('PURCHASE', 'Compras')], default='SALE', max_length=8),
        ),
        migrations.CreateModel(
            name='PurchaseInvoiceImport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external_id', models.CharField(max_length=40)),
                ('access_key', models.CharField(max_length=44, unique=True)),
                ('number', models.CharField(max_length=30)),
                ('series', models.CharField(max_length=10)),
                ('issued_on', models.DateField()),
                ('source', models.JSONField(default=dict)),
                ('approved_source', models.JSONField(default=dict, editable=False)),
                ('fingerprint', models.CharField(max_length=64)),
                ('revision', models.PositiveIntegerField(default=1)),
                ('error', models.CharField(blank=True, max_length=500)),
                ('discrepancy', models.BooleanField(default=False)),
                ('checked_at', models.DateTimeField(auto_now=True)),
                ('connection', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='integrations.blingconnection')),
                ('purchase', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='bling_import', to='purchases.purchase')),
            ],
            options={
                'ordering': ['-issued_on', '-pk'],
                'constraints': [models.UniqueConstraint(fields=('connection', 'external_id'), name='bling_unique_purchase_invoice')],
            },
        ),
        migrations.RunPython(install, uninstall),
    ]
