# Generated by Django 5.2.17 on 2026-09-29 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('integrations', '0006_importrun_kind_purchaseinvoiceimport'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaseinvoiceimport',
            name='rejected',
            field=models.BooleanField(default=False),
        ),
    ]
