# Generated by Django 5.2.17 on 2026-10-06 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('integrations', '0007_purchaseinvoiceimport_rejected'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoiceimport',
            name='review_overrides',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='purchaseinvoiceimport',
            name='review_overrides',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
