# Generated by Django 5.2.17 on 2026-09-17 02:10

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('purchases', '0002_protect_purchase_history'),
        ('sales', '0005_audited_tax_recalculation'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FinancialAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, unique=True, verbose_name='Nome')),
                ('institution', models.CharField(blank=True, max_length=120, verbose_name='Instituição')),
                ('kind', models.CharField(choices=[('BANK', 'Banco'), ('WALLET', 'Carteira digital'), ('CASH', 'Caixa'), ('INVESTMENT', 'Investimento')], max_length=20, verbose_name='Tipo')),
                ('opening_balance', models.DecimalField(decimal_places=2, default=0, max_digits=18, verbose_name='Saldo inicial (R$)')),
                ('opening_date', models.DateField(verbose_name='Data do saldo inicial')),
                ('active', models.BooleanField(default=True, verbose_name='Ativa')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['name', 'pk'],
            },
        ),
        migrations.CreateModel(
            name='FinancialTitle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('fingerprint', models.CharField(blank=True, editable=False, max_length=64)),
                ('direction', models.CharField(choices=[('PAY', 'Pagar'), ('RECEIVE', 'Receber')], max_length=8, verbose_name='Tipo')),
                ('description', models.CharField(max_length=240, verbose_name='Descrição')),
                ('counterparty', models.CharField(blank=True, max_length=240, verbose_name='Favorecido / cliente')),
                ('date', models.DateField(verbose_name='Data de origem')),
                ('due_date', models.DateField(db_index=True, verbose_name='Vencimento')),
                ('amount', models.DecimalField(decimal_places=2, default=0, max_digits=18, verbose_name='Valor principal (R$)')),
                ('settled', models.DecimalField(decimal_places=2, default=0, max_digits=18, verbose_name='Principal liquidado')),
                ('category', models.CharField(choices=[('OPERATING', 'Operacional'), ('FINANCIAL', 'Financeiro / juros'), ('PRINCIPAL', 'Patrimonial / principal'), ('OPENING', 'Pendência de abertura'), ('OTHER', 'A classificar')], default='OTHER', max_length=20, verbose_name='Classificação gerencial')),
                ('opening', models.BooleanField(default=False, verbose_name='Pendência anterior ao corte')),
                ('notes', models.CharField(blank=True, max_length=500, verbose_name='Observação')),
                ('status', models.CharField(choices=[('OPEN', 'Aberto'), ('CANCELLED', 'Cancelado')], default='OPEN', max_length=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('revision', models.PositiveIntegerField(default=0)),
                ('source', models.CharField(default='manual', max_length=30)),
                ('external_id', models.CharField(blank=True, max_length=120)),
                ('account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='finance.financialaccount', verbose_name='Conta prevista')),
                ('actor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('purchase_installment', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='financial_title', to='purchases.purchaseinstallment')),
                ('sale', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='financial_title', to='sales.sale')),
            ],
            options={
                'ordering': ['due_date', 'pk'],
            },
        ),
        migrations.CreateModel(
            name='FinancialOperation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('fingerprint', models.CharField(max_length=64)),
                ('kind', models.CharField(choices=[('SETTLEMENT', 'Liquidação'), ('TRANSFER', 'Transferência'), ('REVERSAL', 'Estorno')], max_length=12)),
                ('status', models.CharField(choices=[('POSTED', 'Realizado'), ('PLANNED', 'Previsto'), ('CANCELLED', 'Cancelado')], default='POSTED', max_length=10)),
                ('date', models.DateField(db_index=True, verbose_name='Data')),
                ('description', models.CharField(max_length=500, verbose_name='Descrição')),
                ('principal', models.DecimalField(decimal_places=2, default=0, max_digits=18, verbose_name='Principal baixado')),
                ('interest', models.DecimalField(decimal_places=2, default=0, max_digits=18, verbose_name='Juros / acréscimos')),
                ('discount', models.DecimalField(decimal_places=2, default=0, max_digits=18, verbose_name='Desconto / abatimento')),
                ('actual', models.DecimalField(decimal_places=2, default=0, max_digits=18, verbose_name='Valor efetivo')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('reversal_of', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='reversal', to='finance.financialoperation')),
                ('title', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='operations', to='finance.financialtitle')),
            ],
            options={
                'ordering': ['-date', '-pk'],
            },
        ),
        migrations.CreateModel(
            name='FinancialEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, default=0, max_digits=18, verbose_name='Valor com sinal')),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='entries', to='finance.financialaccount')),
                ('operation', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='entries', to='finance.financialoperation')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('operation', 'account'), name='finance_one_leg_per_account'), models.CheckConstraint(condition=models.Q(('amount', 0), _negated=True), name='finance_entry_nonzero')],
            },
        ),
        migrations.AddIndex(
            model_name='financialtitle',
            index=models.Index(fields=['status', 'due_date'], name='finance_fin_status_b42126_idx'),
        ),
        migrations.AddConstraint(
            model_name='financialtitle',
            constraint=models.CheckConstraint(condition=models.Q(('amount__gt', 0), ('settled__gte', 0), ('settled__lte', models.F('amount'))), name='finance_title_amounts'),
        ),
        migrations.AddConstraint(
            model_name='financialtitle',
            constraint=models.CheckConstraint(condition=models.Q(('purchase_installment__isnull', True), ('sale__isnull', True), _connector='OR'), name='finance_single_origin'),
        ),
        migrations.AddConstraint(
            model_name='financialoperation',
            constraint=models.CheckConstraint(condition=models.Q(('actual__gte', 0), ('discount__gte', 0), ('interest__gte', 0), ('principal__gte', 0)), name='finance_operation_nonnegative'),
        ),
    ]
