# Generated by Django 5.2.17 on 2026-09-16 14:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        ('inventory', '0004_alter_stockoperation_kind'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='default_stock_location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='inventory.stocklocation', verbose_name='Estoque padrão das vendas'),
        ),
    ]
