# Generated by Django 5.2.17 on 2026-09-16 15:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_company_default_stock_location'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='company',
            options={'permissions': [('manage_configuration', 'Gerenciar configurações da empresa'), ('view_dashboard', 'Visualizar indicadores consolidados'), ('view_dre', 'Visualizar DRE gerencial'), ('view_costs', 'Visualizar custos e margens'), ('view_finance', 'Visualizar contas e saldos financeiros'), ('operate_purchases', 'Cadastrar e receber compras'), ('view_purchase_reports', 'Visualizar relatórios consolidados de compras'), ('operate_sales', 'Lançar vendas operacionais'), ('operate_stock', 'Lançar movimentações autorizadas de estoque'), ('operate_finance', 'Lançar pagamentos e recebimentos')], 'verbose_name': 'Empresa', 'verbose_name_plural': 'Empresa'},
        ),
    ]
