# Generated by Django 5.2.17 on 2026-09-17 09:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_purchase_role_permissions'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='company',
            options={'permissions': [('manage_configuration', 'Gerenciar configurações da empresa'), ('view_dashboard', 'Visualizar indicadores consolidados'), ('view_dre', 'Visualizar DRE gerencial'), ('view_costs', 'Visualizar custos e margens'), ('view_finance', 'Visualizar contas e saldos financeiros'), ('operate_purchases', 'Cadastrar e receber compras'), ('view_purchase_reports', 'Visualizar relatórios consolidados de compras'), ('operate_sales', 'Lançar vendas operacionais'), ('operate_stock', 'Lançar movimentações autorizadas de estoque'), ('operate_finance', 'Lançar pagamentos e recebimentos'), ('operate_expenses', 'Registrar e classificar despesas'), ('manage_expense_rules', 'Gerenciar plano de contas e regras'), ('view_expense_reports', 'Visualizar despesas consolidadas por competência')], 'verbose_name': 'Empresa', 'verbose_name_plural': 'Empresa'},
        ),
    ]
