# Generated by Django 5.2.17 on 2026-09-16 00:32

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StockLocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, unique=True, verbose_name='Nome')),
                ('active', models.BooleanField(default=True, verbose_name='Ativo')),
            ],
            options={
                'ordering': ['name'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='OpeningImport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('digest', models.CharField(max_length=64, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('report', models.JSONField(default=dict)),
                ('actor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='StockOperation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.UUIDField(default=uuid.uuid4, unique=True)),
                ('fingerprint', models.CharField(max_length=64)),
                ('kind', models.CharField(max_length=20)),
                ('date', models.DateField(db_index=True)),
                ('reason', models.CharField(max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('reversal_of', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='reversal', to='inventory.stockoperation')),
            ],
            options={
                'ordering': ['-pk'],
            },
        ),
        migrations.CreateModel(
            name='StockBalance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=4, default=0, max_digits=18)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='balances', to='products.product')),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inventory.stocklocation')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('product', 'location'), name='unique_stock_location'), models.CheckConstraint(condition=models.Q(('quantity__gte', 0)), name='stock_nonnegative')],
            },
        ),
        migrations.CreateModel(
            name='StockMovement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=4, max_digits=18)),
                ('value', models.DecimalField(decimal_places=6, max_digits=24)),
                ('unit_cost', models.DecimalField(decimal_places=6, max_digits=24)),
                ('before_quantity', models.DecimalField(decimal_places=4, max_digits=18)),
                ('after_quantity', models.DecimalField(decimal_places=4, max_digits=18)),
                ('before_value', models.DecimalField(decimal_places=6, max_digits=24)),
                ('after_value', models.DecimalField(decimal_places=6, max_digits=24)),
                ('before_average', models.DecimalField(decimal_places=6, max_digits=24)),
                ('after_average', models.DecimalField(decimal_places=6, max_digits=24)),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inventory.stocklocation')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='movements', to='products.product')),
                ('operation', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='movements', to='inventory.stockoperation')),
            ],
            options={
                'ordering': ['pk'],
                'indexes': [models.Index(fields=['product', 'operation'], name='inventory_s_product_ad90de_idx')],
            },
        ),
    ]
