# Generated by Django 5.2.17 on 2026-09-16 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_alter_stockoperation_kind'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stockoperation',
            name='kind',
            field=models.CharField(choices=[('OPENING', 'Saldo inicial'), ('RECEIPT', 'Entrada'), ('ISSUE', 'Saída'), ('ADJUST_IN', 'Ajuste: acréscimo'), ('ADJUST_OUT', 'Ajuste: redução'), ('TRANSFER', 'Transferência'), ('SPLIT', 'Fracionamento'), ('KIT_ISSUE', 'Saída de kit'), ('REVALUE', 'Correção de custo'), ('REVERSAL', 'Estorno'), ('SALE_OUT', 'Venda'), ('SALE_RETURN', 'Cancelamento de venda')], max_length=20),
        ),
    ]
