# Generated by Django 5.2.17 on 2026-09-22 12:35

from django.db import migrations, models
from decimal import Decimal, ROUND_HALF_UP


def populate_local_costs(apps, schema_editor):
    Balance = apps.get_model('inventory', 'StockBalance')
    Movement = apps.get_model('inventory', 'StockMovement')
    Product = apps.get_model('products', 'Product')
    alias = schema_editor.connection.alias
    if schema_editor.connection.vendor == 'postgresql':
        schema_editor.execute('SELECT pg_advisory_xact_lock(763820102)')
    for balance in Balance.objects.using(alias).all().iterator():
        moves = Movement.objects.using(alias).filter(product_id=balance.product_id, location_id=balance.location_id)
        totals = moves.aggregate(q=models.Sum('quantity'), v=models.Sum('value'))
        quantity, value = totals['q'] or Decimal(0), totals['v'] or Decimal(0)
        if quantity != balance.quantity or value < 0 or (quantity == 0 and value != 0):
            raise RuntimeError(f'Saldo local {balance.pk} exige conciliação antes do MVet 1.5. Nenhum histórico foi alterado.')
        last = moves.order_by('-pk').first()
        balance.value = value
        balance.average_cost = (value / quantity).quantize(Decimal('0.000001'), rounding=ROUND_HALF_UP) if quantity else (last.unit_cost if last else Decimal(0))
        balance.save(using=alias, update_fields=['value', 'average_cost'])
    for product in Product.objects.using(alias).filter(kind='SIMPLE').iterator():
        totals = Balance.objects.using(alias).filter(product_id=product.pk).aggregate(q=models.Sum('quantity'), v=models.Sum('value'))
        if product.quantity != (totals['q'] or 0) or product.value != (totals['v'] or 0):
            raise RuntimeError(f'Produto {product.pk} exige conciliação dos saldos locais antes do MVet 1.5.')



class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0005_alter_stockoperation_kind'),
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='stockbalance',
            name='average_cost',
            field=models.DecimalField(decimal_places=6, default=0, max_digits=24),
        ),
        migrations.AddField(
            model_name='stockbalance',
            name='value',
            field=models.DecimalField(decimal_places=6, default=0, max_digits=24),
        ),
        migrations.AddField(
            model_name='stockmovement',
            name='before_local_average',
            field=models.DecimalField(decimal_places=6, editable=False, max_digits=24, null=True),
        ),
        migrations.RunPython(populate_local_costs, migrations.RunPython.noop),
        migrations.AddConstraint(
            model_name='stockbalance',
            constraint=models.CheckConstraint(condition=models.Q(('average_cost__gte', 0), ('value__gte', 0)), name='stock_local_value_nonnegative'),
        ),
    ]
