# Generated by Django 5.2.17 on 2026-10-07 22:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0007_remove_unused_duplicate_full'),
        ('products', '0002_remove_product_product_nonnegative_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='stockbalance',
            name='stock_nonnegative',
        ),
        migrations.RemoveConstraint(
            model_name='stockbalance',
            name='stock_local_value_nonnegative',
        ),
        migrations.AddField(
            model_name='stockmovement',
            name='cost_variance',
            field=models.DecimalField(decimal_places=6, default=0, editable=False, max_digits=24),
        ),
        migrations.AddConstraint(
            model_name='stockbalance',
            constraint=models.CheckConstraint(condition=models.Q(('average_cost__gte', 0)), name='stock_cost_nonnegative'),
        ),
        migrations.AddConstraint(
            model_name='stockbalance',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('quantity__gt', 0), ('value__gte', 0)), models.Q(('quantity__lt', 0), ('value__lte', 0)), models.Q(('quantity', 0), ('value', 0)), _connector='OR'), name='stock_value_sign'),
        ),
    ]
