# Generated by Django 5.2.17 on 2026-10-10 07:01

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RecurrenceRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('result', models.CharField(choices=[('INTERESTED', 'Respondeu — interessado'), ('NOT_NOW', 'Respondeu — sem interesse no momento'), ('CALLBACK', 'Pediu retorno'), ('QUOTE_REQUEST', 'Cotação solicitada'), ('QUOTE_SENT', 'Cotação enviada'), ('NEGOTIATION', 'Negociação em andamento'), ('SALE', 'Venda realizada'), ('WAITING', 'Mensagem enviada — aguardando resposta'), ('NO_REPLY', 'Mensagem enviada — não respondeu'), ('READ_NO_REPLY', 'Mensagem enviada — visualizou e não respondeu'), ('NO_ANSWER', 'Ligação — não atendeu'), ('INVALID', 'Contato inválido'), ('WRONG_NUMBER', 'Número incorreto'), ('OUTSIDE', 'Fora do perfil'), ('OPT_OUT', 'Pediu para não ser contatado'), ('COLD', 'Contato frio'), ('OTHER', 'Outro')], max_length=25, unique=True)),
                ('days', models.PositiveIntegerField(default=7, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(3650)], verbose_name='Retornar após (dias)')),
                ('allow_manual', models.BooleanField(default=True, verbose_name='Funcionário pode escolher outra data')),
            ],
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=180, verbose_name='Nome')),
                ('phone', models.CharField(blank=True, db_index=True, max_length=20, verbose_name='Telefone / WhatsApp')),
                ('email', models.EmailField(blank=True, db_index=True, max_length=254, verbose_name='E-mail')),
                ('city', models.CharField(blank=True, max_length=120, verbose_name='Cidade (recomendada)')),
                ('uf', models.CharField(blank=True, max_length=2, verbose_name='UF')),
                ('company', models.CharField(blank=True, max_length=180, verbose_name='Empresa / fazenda')),
                ('segment', models.CharField(blank=True, choices=[('SWINE', 'Suinocultura'), ('MILK', 'Leite'), ('BEEF', 'Corte / confinamento'), ('POULTRY', 'Avicultura'), ('OTHER', 'Outro')], max_length=20, verbose_name='Segmento')),
                ('origin', models.CharField(choices=[('BASE', 'Base Mercadovet'), ('WHATSAPP', 'WhatsApp direto'), ('CALL', 'Ligação'), ('STORE', 'Loja física'), ('REFERRAL', 'Indicação'), ('SITE', 'Site'), ('VISIT', 'Visita comercial'), ('EVENT', 'Evento'), ('IMPORT', 'Importação'), ('OTHER', 'Outro')], default='OTHER', max_length=20, verbose_name='Origem')),
                ('kind', models.CharField(choices=[('LEAD', 'Lead'), ('PROSPECT', 'Prospect'), ('CLIENT', 'Cliente'), ('FORMER', 'Ex-cliente'), ('PARTNER', 'Parceiro'), ('OTHER', 'Outro')], default='LEAD', max_length=20, verbose_name='Tipo')),
                ('notes', models.TextField(blank=True, max_length=10000, verbose_name='Observações')),
                ('commercial_info', models.TextField(blank=True, max_length=10000, verbose_name='Informações comerciais importantes')),
                ('state', models.CharField(choices=[('ACTIVE', 'Ativo'), ('WAITING', 'Aguardando resposta'), ('PAUSED', 'Pausado'), ('APPROVAL', 'Solicitação de inativação'), ('INACTIVE', 'Inativo'), ('DNC', 'Não contatar')], db_index=True, default='ACTIVE', max_length=20)),
                ('next_date', models.DateField(blank=True, db_index=True, null=True, verbose_name='Próximo contato')),
                ('next_reason', models.CharField(default='Primeiro contato', max_length=300, verbose_name='Motivo da próxima ação')),
                ('last_at', models.DateTimeField(blank=True, null=True)),
                ('last_result', models.CharField(blank=True, choices=[('INTERESTED', 'Respondeu — interessado'), ('NOT_NOW', 'Respondeu — sem interesse no momento'), ('CALLBACK', 'Pediu retorno'), ('QUOTE_REQUEST', 'Cotação solicitada'), ('QUOTE_SENT', 'Cotação enviada'), ('NEGOTIATION', 'Negociação em andamento'), ('SALE', 'Venda realizada'), ('WAITING', 'Mensagem enviada — aguardando resposta'), ('NO_REPLY', 'Mensagem enviada — não respondeu'), ('READ_NO_REPLY', 'Mensagem enviada — visualizou e não respondeu'), ('NO_ANSWER', 'Ligação — não atendeu'), ('INVALID', 'Contato inválido'), ('WRONG_NUMBER', 'Número incorreto'), ('OUTSIDE', 'Fora do perfil'), ('OPT_OUT', 'Pediu para não ser contatado'), ('COLD', 'Contato frio'), ('OTHER', 'Outro')], max_length=25)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('revision', models.PositiveIntegerField(default=0)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='crm_contacts', to=settings.AUTH_USER_MODEL, verbose_name='Responsável')),
            ],
            options={
                'ordering': ['name', 'pk'],
            },
        ),
        migrations.CreateModel(
            name='ContactEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('action', models.CharField(max_length=60)),
                ('note', models.TextField(blank=True)),
                ('before', models.JSONField(default=dict)),
                ('after', models.JSONField(default=dict)),
                ('actor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('contact', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='events', to='crm.contact')),
            ],
            options={
                'ordering': ['-created_at', '-pk'],
            },
        ),
        migrations.CreateModel(
            name='ImportBatch',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('first_date', models.DateField()),
                ('rows', models.JSONField(default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('committed_at', models.DateTimeField(null=True)),
                ('report', models.JSONField(default=list)),
                ('actor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='InactivationRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.CharField(choices=[('NO_INTEREST', 'Sem interesse'), ('OUTSIDE', 'Fora do perfil'), ('INVALID', 'Número inválido'), ('CLOSED', 'Empresa encerrou'), ('OPT_OUT', 'Pediu para não receber contato'), ('NO_REPLY', 'Muitas tentativas sem retorno'), ('COMPETITOR', 'Perdido para concorrente'), ('OTHER', 'Outro')], max_length=20, verbose_name='Motivo')),
                ('justification', models.TextField(max_length=5000, verbose_name='Justificativa')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('decision', models.CharField(choices=[('PENDING', 'Pendente'), ('APPROVED', 'Aprovada'), ('REJECTED', 'Recusada')], default='PENDING', max_length=10)),
                ('decided_at', models.DateTimeField(null=True)),
                ('decision_note', models.TextField(blank=True, max_length=5000)),
                ('actor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('contact', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='requests', to='crm.contact')),
                ('decided_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['created_at', 'pk'],
            },
        ),
        migrations.CreateModel(
            name='Interaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.UUIDField(default=uuid.uuid4, unique=True)),
                ('occurred_at', models.DateTimeField(verbose_name='Data e horário')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('channel', models.CharField(choices=[('WHATSAPP', 'WhatsApp'), ('CALL', 'Ligação'), ('EMAIL', 'E-mail'), ('PERSON', 'Presencial'), ('OTHER', 'Outro')], max_length=20, verbose_name='Canal')),
                ('kind', models.CharField(choices=[('ATTEMPT', 'Tentativa de contato'), ('CONVERSATION', 'Conversa'), ('FOLLOWUP', 'Retorno'), ('VISIT', 'Visita'), ('OTHER', 'Outro')], default='CONVERSATION', max_length=20, verbose_name='Tipo')),
                ('sent', models.TextField(blank=True, max_length=20000, verbose_name='Mensagem enviada')),
                ('received', models.TextField(blank=True, max_length=20000, verbose_name='Mensagem recebida')),
                ('read_state', models.CharField(choices=[('UNKNOWN', 'Não informado'), ('UNSURE', 'Não sei se visualizou'), ('UNREAD', 'Não visualizou'), ('READ', 'Visualizou'), ('REPLIED', 'Respondeu')], default='UNKNOWN', max_length=20, verbose_name='Visualização (manual)')),
                ('result', models.CharField(choices=[('INTERESTED', 'Respondeu — interessado'), ('NOT_NOW', 'Respondeu — sem interesse no momento'), ('CALLBACK', 'Pediu retorno'), ('QUOTE_REQUEST', 'Cotação solicitada'), ('QUOTE_SENT', 'Cotação enviada'), ('NEGOTIATION', 'Negociação em andamento'), ('SALE', 'Venda realizada'), ('WAITING', 'Mensagem enviada — aguardando resposta'), ('NO_REPLY', 'Mensagem enviada — não respondeu'), ('READ_NO_REPLY', 'Mensagem enviada — visualizou e não respondeu'), ('NO_ANSWER', 'Ligação — não atendeu'), ('INVALID', 'Contato inválido'), ('WRONG_NUMBER', 'Número incorreto'), ('OUTSIDE', 'Fora do perfil'), ('OPT_OUT', 'Pediu para não ser contatado'), ('COLD', 'Contato frio'), ('OTHER', 'Outro')], max_length=25, verbose_name='Resultado')),
                ('internal_note', models.TextField(blank=True, max_length=10000, verbose_name='Observação interna')),
                ('next_date', models.DateField(blank=True, null=True)),
                ('next_reason', models.CharField(blank=True, max_length=300)),
                ('rule_days', models.PositiveIntegerField(null=True)),
                ('manual_date', models.BooleanField(default=False)),
                ('actor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('contact', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='interactions', to='crm.contact')),
            ],
            options={
                'ordering': ['-occurred_at', '-pk'],
            },
        ),
        migrations.AddConstraint(
            model_name='contact',
            constraint=models.CheckConstraint(condition=models.Q(('email', ''), ('phone', ''), _negated=True), name='crm_contact_reachable'),
        ),
        migrations.AddConstraint(
            model_name='contact',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('state__in', ['ACTIVE', 'WAITING', 'PAUSED']), _negated=True), ('next_date__isnull', False), _connector='OR'), name='crm_active_next_action'),
        ),
        migrations.AddConstraint(
            model_name='contact',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('state__in', ['DNC', 'INACTIVE', 'APPROVAL']), _negated=True), ('next_date__isnull', True), _connector='OR'), name='crm_stopped_no_action'),
        ),
        migrations.AddConstraint(
            model_name='contact',
            constraint=models.UniqueConstraint(condition=models.Q(('phone', ''), _negated=True), fields=('phone',), name='crm_unique_phone'),
        ),
        migrations.AddConstraint(
            model_name='contact',
            constraint=models.UniqueConstraint(condition=models.Q(('email', ''), _negated=True), fields=('email',), name='crm_unique_email'),
        ),
        migrations.AddConstraint(
            model_name='inactivationrequest',
            constraint=models.UniqueConstraint(condition=models.Q(('decision', 'PENDING')), fields=('contact',), name='crm_one_pending_request'),
        ),
    ]
