"""Independent capabilities. Legacy aliases preserve existing roles until edited."""
CAPABILITIES = {
    'view_sales': ('Consultar vendas individuais', ('operate_sales', 'view_costs', 'view_margins')),
    'view_stock': ('Consultar produtos e quantidades', ('operate_stock', 'operate_sales', 'operate_purchases', 'view_purchase_reports', 'view_costs')),
    'view_margins': ('Consultar margens de vendas', ()),
    'view_sales_report': ('Consultar relatório detalhado de vendas', ()),
    'confirm_sales': ('Confirmar vendas e baixar estoque', ('operate_sales',)),
    'cancel_sales': ('Cancelar vendas', ('operate_sales',)),
    'manage_products': ('Cadastrar e editar produtos e kits', ('operate_stock',)),
    'remove_products': ('Excluir ou inativar produtos', ('operate_stock',)),
    'manage_stock_catalogs': ('Gerenciar locais, marcas e categorias', ('operate_stock',)),
    'transfer_stock': ('Transferir entre estoques', ('operate_stock',)),
    'adjust_stock': ('Ajustar quantidade de estoque', ('operate_stock',)),
    'receive_stock': ('Registrar entrada e abertura de estoque', ('operate_stock',)),
    'fraction_stock': ('Fracionar produtos', ('operate_stock',)),
    'adjust_stock_cost': ('Corrigir custo do estoque', ('operate_stock',)),
    'reverse_stock': ('Estornar movimentação de estoque', ('operate_stock',)),
    'manage_suppliers': ('Cadastrar e editar fornecedores', ('operate_purchases',)),
    'confirm_purchases': ('Confirmar compras', ('operate_purchases',)),
    'receive_purchases': ('Receber mercadorias compradas', ('operate_purchases',)),
    'cancel_purchases': ('Cancelar compras', ('operate_purchases',)),
    'manage_financial_accounts': ('Cadastrar e editar contas bancárias', ('operate_finance',)),
    'create_financial_titles': ('Criar contas a pagar ou receber', ('operate_finance',)),
    'schedule_financial_titles': ('Alterar vencimentos e conta prevista', ('operate_finance',)),
    'pay_titles': ('Efetuar pagamentos', ('operate_finance',)),
    'receive_titles': ('Efetuar recebimentos', ('operate_finance',)),
    'transfer_finance': ('Transferir entre contas bancárias', ('operate_finance',)),
    'reverse_finance': ('Estornar pagamentos e transferências', ('operate_finance',)),
    'cancel_financial_titles': ('Cancelar títulos financeiros', ('operate_finance',)),
    'cancel_expenses': ('Cancelar despesas', ('operate_expenses',)),
    'reclassify_expenses': ('Corrigir classificação das despesas', ('operate_expenses',)),
    'manage_recurrence': ('Gerar e encerrar despesas recorrentes', ('operate_expenses',)),
    'manage_channels': ('Gerenciar canais de venda', ('manage_configuration',)),
    'manage_taxes': ('Gerenciar regras e vigências tributárias', ('manage_configuration',)),
    'retroactive_taxes': ('Recalcular imposto de vendas anteriores', ('manage_configuration',)),
    'manage_alerts': ('Configurar e processar alertas', ('manage_configuration',)),
    **{'export_'+name: ('Exportar '+label+' em Excel e PDF', ()) for name,label in [
        ('sales','vendas'), ('stock','estoque'), ('purchases','compras'),
        ('finance','títulos e caixa'), ('expenses','despesas'), ('dre','DRE'), ('dashboard','indicadores')]},
}

LABELS = {
    'view_dashboard': 'Consultar faturamento consolidado (sem margens)',
    'view_costs': 'Consultar custos, CMV e valorização de estoque',
    'view_finance': 'Consultar saldos bancários e fluxo de caixa',
    'view_dre': 'Consultar DRE e resultado acumulado (inclui custos e margens)',
}
