# Generated by Django 5.2.17 on 2026-09-16 15:40

import django.core.validators
import django.db.models.deletion
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('inventory', '0005_alter_stockoperation_kind'),
        ('products', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('legal_name', models.CharField(max_length=240, verbose_name='Razão social / nome')),
                ('trade_name', models.CharField(blank=True, max_length=240, verbose_name='Nome fantasia')),
                ('document', models.CharField(blank=True, max_length=18, verbose_name='CNPJ / CPF')),
                ('contact', models.CharField(blank=True, max_length=120, verbose_name='Contato')),
                ('phone', models.CharField(blank=True, max_length=40, verbose_name='Telefone')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='E-mail')),
                ('notes', models.TextField(blank=True, max_length=3000, verbose_name='Observações')),
                ('active', models.BooleanField(default=True, verbose_name='Ativo')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['legal_name', 'pk'],
                'constraints': [models.UniqueConstraint(condition=models.Q(('document', ''), _negated=True), fields=('document',), name='purchase_supplier_document_unique')],
            },
        ),
        migrations.CreateModel(
            name='Purchase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('fingerprint', models.CharField(editable=False, max_length=64)),
                ('revision', models.PositiveIntegerField(default=0, editable=False)),
                ('document', models.CharField(max_length=60, verbose_name='NF / documento')),
                ('series', models.CharField(blank=True, max_length=20, verbose_name='Série')),
                ('date', models.DateField(db_index=True, verbose_name='Data da compra')),
                ('discount', models.DecimalField(decimal_places=2, default=0, max_digits=18, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Desconto (R$)')),
                ('freight', models.DecimalField(decimal_places=2, default=0, max_digits=18, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Frete de aquisição (R$)')),
                ('other_costs', models.DecimalField(decimal_places=2, default=0, max_digits=18, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Outros custos de aquisição (R$)')),
                ('products_total', models.DecimalField(decimal_places=2, default=0, max_digits=18, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Total dos produtos')),
                ('total', models.DecimalField(decimal_places=2, default=0, max_digits=18, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Total da compra')),
                ('notes', models.TextField(blank=True, max_length=3000, verbose_name='Observações')),
                ('status', models.CharField(choices=[('DRAFT', 'Rascunho'), ('ORDERED', 'Confirmada / a receber'), ('RECEIVED', 'Recebida'), ('CANCELLED', 'Cancelada')], db_index=True, default='DRAFT', max_length=12)),
                ('received_date', models.DateField(editable=False, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('confirmed_at', models.DateTimeField(editable=False, null=True)),
                ('received_at', models.DateTimeField(editable=False, null=True)),
                ('cancelled_at', models.DateTimeField(editable=False, null=True)),
                ('cancellation_reason', models.CharField(blank=True, max_length=500)),
                ('source', models.CharField(default='manual', max_length=40)),
                ('external_id', models.CharField(blank=True, max_length=120)),
                ('cancelled_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='cancelled_purchases', to=settings.AUTH_USER_MODEL)),
                ('confirmed_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='confirmed_purchases', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_purchases', to=settings.AUTH_USER_MODEL)),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inventory.stocklocation', verbose_name='Estoque de destino')),
                ('receipt', models.OneToOneField(editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='purchase_receipt', to='inventory.stockoperation')),
                ('received_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='received_purchases', to=settings.AUTH_USER_MODEL)),
                ('reversal', models.OneToOneField(editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='purchase_reversal', to='inventory.stockoperation')),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='purchases', to='purchases.supplier', verbose_name='Fornecedor')),
            ],
            options={
                'ordering': ['-date', '-pk'],
            },
        ),
        migrations.CreateModel(
            name='PurchaseInstallment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.PositiveIntegerField()),
                ('due_date', models.DateField(db_index=True, verbose_name='Vencimento')),
                ('amount', models.DecimalField(decimal_places=2, default=0, max_digits=18, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Valor (R$)')),
                ('status', models.CharField(choices=[('PENDING', 'Pendente'), ('CANCELLED', 'Cancelada')], default='PENDING', max_length=12)),
                ('notes', models.CharField(blank=True, max_length=500, verbose_name='Observação')),
                ('purchase', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='installments', to='purchases.purchase')),
            ],
            options={
                'ordering': ['number', 'pk'],
                'constraints': [models.UniqueConstraint(fields=('purchase', 'number'), name='purchase_installment_number'), models.CheckConstraint(condition=models.Q(('amount__gt', 0)), name='purchase_installment_positive')],
            },
        ),
        migrations.CreateModel(
            name='PurchaseItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=4, max_digits=18, validators=[django.core.validators.MinValueValidator(Decimal('0.0001'))], verbose_name='Quantidade')),
                ('unit_cost', models.DecimalField(decimal_places=6, max_digits=24, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Preço unitário (R$)')),
                ('subtotal', models.DecimalField(decimal_places=2, default=0, max_digits=18, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Subtotal')),
                ('allocated_total', models.DecimalField(decimal_places=2, default=0, max_digits=18, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Valor incorporado ao estoque')),
                ('landed_unit_cost', models.DecimalField(decimal_places=6, default=0, max_digits=24)),
                ('sku_snapshot', models.CharField(blank=True, max_length=60)),
                ('name_snapshot', models.CharField(blank=True, max_length=240)),
                ('movement', models.OneToOneField(editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, to='inventory.stockmovement')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='products.product')),
                ('purchase', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='items', to='purchases.purchase')),
            ],
            options={
                'ordering': ['pk'],
                'constraints': [models.CheckConstraint(condition=models.Q(('allocated_total__gte', 0), ('quantity__gt', 0), ('subtotal__gte', 0), ('unit_cost__gte', 0)), name='purchase_item_nonnegative')],
            },
        ),
        migrations.AddIndex(
            model_name='purchase',
            index=models.Index(fields=['supplier', 'date'], name='purchases_p_supplie_256998_idx'),
        ),
        migrations.AddConstraint(
            model_name='purchase',
            constraint=models.UniqueConstraint(fields=('supplier', 'document', 'series'), name='purchase_unique_document'),
        ),
        migrations.AddConstraint(
            model_name='purchase',
            constraint=models.CheckConstraint(condition=models.Q(('discount__gte', 0), ('freight__gte', 0), ('other_costs__gte', 0), ('products_total__gte', 0), ('total__gte', 0)), name='purchase_nonnegative'),
        ),
        migrations.AddConstraint(
            model_name='purchase',
            constraint=models.CheckConstraint(condition=models.Q(('discount__lte', models.F('products_total'))), name='purchase_discount_limit'),
        ),
    ]
