# Generated by Django 5.2.17 on 2026-10-06 19:14

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0002_protect_expenses'),
        ('inventory', '0007_remove_unused_duplicate_full'),
        ('products', '0001_initial'),
        ('purchases', '0002_protect_purchase_history'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchase',
            name='acquisition_kind',
            field=models.CharField(choices=[('NORMAL', 'Compra com financeiro'), ('BONUS', 'Bonificação sem financeiro')], default='NORMAL', max_length=10, verbose_name='Tipo de entrada'),
        ),
        migrations.AddField(
            model_name='purchaseitem',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='purchase_items', to='expenses.chartofaccount', verbose_name='Categoria sem estoque'),
        ),
        migrations.AddField(
            model_name='purchaseitem',
            name='category_snapshot',
            field=models.JSONField(blank=True, default=dict, editable=False),
        ),
        migrations.AddField(
            model_name='purchaseitem',
            name='moves_stock',
            field=models.BooleanField(default=True, verbose_name='Movimentar estoque'),
        ),
        migrations.AddField(
            model_name='purchaseitem',
            name='nonstock_total',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=18, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Valor sem estoque'),
        ),
        migrations.AlterField(
            model_name='purchaseitem',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='products.product'),
        ),
        migrations.AddConstraint(
            model_name='purchaseitem',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('allocated_total', 0), ('moves_stock', False)), models.Q(('category__isnull', True), ('moves_stock', True), ('nonstock_total', 0), ('product__isnull', False)), _connector='OR'), name='purchase_item_stock_consistent'),
        ),
        migrations.AddConstraint(
            model_name='purchaseitem',
            constraint=models.CheckConstraint(condition=models.Q(('nonstock_total__gte', 0)), name='purchase_item_nonstock_nonnegative'),
        ),
    ]
