# Generated by Django 5.2.17 on 2026-10-08 20:11

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0002_protect_expenses'),
        ('inventory', '0008_remove_stockbalance_stock_nonnegative_and_more'),
        ('products', '0002_remove_product_product_nonnegative_and_more'),
        ('purchases', '0004_protect_cost_variance_receipts'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaseitem',
            name='discount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=18, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Desconto deste item (R$)'),
        ),
        migrations.AddConstraint(
            model_name='purchaseitem',
            constraint=models.CheckConstraint(condition=models.Q(('discount__gte', 0), ('discount__lte', models.F('subtotal'))), name='purchase_item_discount_limit'),
        ),
    ]
