# Generated by Django 5.2.17 on 2026-09-17 09:51

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('finance', '0003_ledger_protection'),
        ('purchases', '0002_protect_purchase_history'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ChartOfAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=47, unique=True, verbose_name='Código')),
                ('name', models.CharField(max_length=180, verbose_name='Nome')),
                ('nature', models.CharField(choices=[('OPERATING', 'Despesa operacional'), ('FINANCIAL', 'Despesa financeira'), ('ASSET', 'Ativo'), ('LIABILITY', 'Passivo'), ('EQUITY', 'Patrimônio'), ('REVENUE', 'Receita')], max_length=12, verbose_name='Natureza')),
                ('postable', models.BooleanField(default=True, verbose_name='Aceita lançamentos')),
                ('active', models.BooleanField(default=True, verbose_name='Ativa')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='children', to='expenses.chartofaccount', verbose_name='Categoria superior')),
            ],
            options={
                'ordering': ['code', 'pk'],
            },
        ),
        migrations.CreateModel(
            name='ClassificationRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=180, verbose_name='Nome')),
                ('priority', models.PositiveIntegerField(default=100, verbose_name='Prioridade (menor primeiro)')),
                ('field', models.CharField(choices=[('description', 'Descrição'), ('counterparty', 'Favorecido'), ('supplier_document', 'CPF/CNPJ do fornecedor')], max_length=20, verbose_name='Campo')),
                ('operator', models.CharField(choices=[('CONTAINS', 'Contém'), ('EQUALS', 'Igual a'), ('STARTS', 'Começa com')], max_length=12, verbose_name='Operador')),
                ('value', models.CharField(max_length=240, verbose_name='Valor procurado')),
                ('active', models.BooleanField(default=True, verbose_name='Ativa')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='expenses.chartofaccount', verbose_name='Categoria resultante')),
            ],
            options={
                'ordering': ['priority', 'pk'],
            },
        ),
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('fingerprint', models.CharField(editable=False, max_length=64)),
                ('document_date', models.DateField(verbose_name='Data do documento / contrato')),
                ('competence', models.DateField(db_index=True, verbose_name='Competência')),
                ('description', models.CharField(max_length=240, verbose_name='Descrição')),
                ('counterparty', models.CharField(blank=True, max_length=240, verbose_name='Favorecido')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=18, verbose_name='Valor (R$)')),
                ('category_snapshot', models.JSONField(blank=True, default=dict, editable=False)),
                ('classification', models.CharField(choices=[('MANUAL', 'Manual'), ('RULE', 'Regra automática'), ('NONE', 'A classificar')], default='NONE', max_length=12)),
                ('rule_snapshot', models.JSONField(blank=True, default=dict, editable=False)),
                ('cost_center', models.CharField(blank=True, max_length=120, verbose_name='Centro de custo')),
                ('notes', models.CharField(blank=True, max_length=500, verbose_name='Observação')),
                ('status', models.CharField(choices=[('ACTIVE', 'Registrada'), ('CANCELLED', 'Cancelada')], db_index=True, default='ACTIVE', max_length=12)),
                ('recurrence_index', models.PositiveIntegerField(default=0, editable=False)),
                ('recurrence_enabled', models.BooleanField(default=False, verbose_name='Despesa recorrente mensal')),
                ('revision', models.PositiveIntegerField(default=0, editable=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('cancelled_at', models.DateTimeField(editable=False, null=True)),
                ('cancellation_reason', models.CharField(blank=True, max_length=500)),
                ('actor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='expenses', to='expenses.chartofaccount', verbose_name='Plano de contas')),
                ('recurrence_of', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='occurrences', to='expenses.expense')),
                ('supplier', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='purchases.supplier', verbose_name='Fornecedor cadastrado')),
                ('title', models.OneToOneField(editable=False, on_delete=django.db.models.deletion.PROTECT, related_name='expense', to='finance.financialtitle')),
            ],
            options={
                'ordering': ['-competence', '-pk'],
            },
        ),
        migrations.CreateModel(
            name='ExpenseRevision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.PositiveIntegerField()),
                ('reason', models.CharField(max_length=500)),
                ('before', models.JSONField()),
                ('after', models.JSONField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('expense', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='revisions', to='expenses.expense')),
            ],
        ),
        migrations.AddIndex(
            model_name='expense',
            index=models.Index(fields=['status', 'competence'], name='expenses_ex_status_3222de_idx'),
        ),
        migrations.AddIndex(
            model_name='expense',
            index=models.Index(fields=['category', 'competence'], name='expenses_ex_categor_3d5a51_idx'),
        ),
        migrations.AddConstraint(
            model_name='expense',
            constraint=models.CheckConstraint(condition=models.Q(('amount__gt', 0)), name='expense_positive'),
        ),
        migrations.AddConstraint(
            model_name='expense',
            constraint=models.UniqueConstraint(condition=models.Q(('recurrence_of__isnull', False)), fields=('recurrence_of', 'recurrence_index'), name='expense_unique_occurrence'),
        ),
        migrations.AddConstraint(
            model_name='expenserevision',
            constraint=models.UniqueConstraint(fields=('expense', 'number'), name='expense_revision_unique'),
        ),
    ]
