# Generated by Django 5.2.17 on 2026-10-10 17:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0002_protect_expenses'),
        ('finance', '0003_ledger_protection'),
    ]

    operations = [
        migrations.AddField(
            model_name='chartofaccount',
            name='seed_key',
            field=models.CharField(blank=True, editable=False, max_length=80, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='chartofaccount',
            name='nature',
            field=models.CharField(choices=[('OPERATING', 'Despesa operacional'), ('FINANCIAL', 'Despesa financeira'), ('ASSET', 'Ativo'), ('LIABILITY', 'Passivo'), ('EQUITY', 'Patrimônio'), ('REVENUE', 'Receita'), ('DEPRECIATION', 'Depreciação / amortização'), ('UNCLASSIFIED', 'A classificar'), ('GROUP', 'Grupo de naturezas diversas')], max_length=12, verbose_name='Natureza'),
        ),
        migrations.AlterField(
            model_name='expense',
            name='title',
            field=models.OneToOneField(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='expense', to='finance.financialtitle'),
        ),
    ]
