# Generated by Django 5.2.17 on 2026-10-10 17:47

from django.db import migrations


def adjust_guard(apps, schema_editor, reverse=False):
    if schema_editor.connection.vendor != 'postgresql': return
    with schema_editor.connection.cursor() as cursor:
        cursor.execute("SELECT pg_get_functiondef('mvet_expense_protected()'::regprocedure)")
        definition=cursor.fetchone()[0]
    old="IF NEW.status='CANCELLED' AND NOT EXISTS"
    new="IF NEW.status='CANCELLED' AND NEW.title_id IS NOT NULL AND NOT EXISTS"
    schema_editor.execute(definition.replace(new,old) if reverse else definition.replace(old,new))


def restore_guard(apps, schema_editor):
    adjust_guard(apps, schema_editor, reverse=True)


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0003_chartofaccount_seed_key_alter_chartofaccount_nature_and_more'),
    ]

    operations = [migrations.RunPython(adjust_guard, restore_guard)]
