# Generated by Django 5.2.17 on 2026-10-10 17:49

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0004_protect_noncash_expenses'),
        ('finance', '0003_ledger_protection'),
        ('purchases', '0005_purchaseitem_discount_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='expense',
            constraint=models.CheckConstraint(condition=models.Q(('title__isnull', False), models.Q(('category_snapshot__has_key', 'nature'), ('category_snapshot__nature', 'DEPRECIATION')), _connector='OR'), name='expense_noncash_category'),
        ),
    ]
