# Generated by Django 5.2.17 on 2026-09-17 19:52

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AlertConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stock', models.BooleanField(default=True, verbose_name='Estoque mínimo')),
                ('margin', models.BooleanField(default=True, verbose_name='Margem baixa ou negativa')),
                ('due', models.BooleanField(default=True, verbose_name='Contas a pagar e receber')),
                ('due_days', models.PositiveSmallIntegerField(default=3, validators=[django.core.validators.MaxValueValidator(90)], verbose_name='Antecedência em dias')),
                ('backup', models.BooleanField(default=False, verbose_name='Monitorar backup')),
                ('backup_hours', models.PositiveSmallIntegerField(default=36, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(720)], verbose_name='Prazo máximo sem backup (horas)')),
                ('backup_started_at', models.DateTimeField(blank=True, editable=False, null=True)),
                ('last_refresh', models.DateTimeField(blank=True, editable=False, null=True)),
            ],
            options={
                'constraints': [models.CheckConstraint(condition=models.Q(('pk', 1)), name='alert_configuration_singleton'), models.CheckConstraint(condition=models.Q(('backup_hours__gte', 1), ('backup_hours__lte', 720), ('due_days__lte', 90)), name='alert_configuration_limits')],
            },
        ),
        migrations.CreateModel(
            name='BackupEvidence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('occurred_at', models.DateTimeField(auto_now_add=True)),
                ('success', models.BooleanField()),
                ('size_bytes', models.PositiveBigIntegerField(default=0)),
                ('sha256', models.CharField(blank=True, max_length=64)),
            ],
            options={
                'ordering': ['-occurred_at', '-pk'],
                'constraints': [models.CheckConstraint(condition=models.Q(models.Q(('sha256', ''), ('size_bytes', 0), ('success', False)), models.Q(('size_bytes__gt', 0), ('success', True), models.Q(('sha256', ''), _negated=True)), _connector='OR'), name='backup_evidence_content')],
            },
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('STOCK', 'Estoque mínimo'), ('MARGIN', 'Margem de venda'), ('DUE', 'Contas a pagar e receber'), ('BACKUP', 'Backup')], max_length=10)),
                ('entity_id', models.PositiveBigIntegerField()),
                ('title', models.CharField(max_length=260)),
                ('description', models.TextField()),
                ('severity', models.CharField(choices=[('INFO', 'Informação'), ('WARNING', 'Atenção'), ('CRITICAL', 'Crítico')], max_length=10)),
                ('fingerprint', models.CharField(max_length=64)),
                ('revision', models.PositiveIntegerField(default=1)),
                ('active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('resolved_at', models.DateTimeField(null=True)),
            ],
            options={
                'ordering': ['-updated_at', '-pk'],
                'indexes': [models.Index(fields=['kind', 'active', '-updated_at'], name='notificatio_kind_7839d2_idx')],
                'constraints': [models.UniqueConstraint(fields=('kind', 'entity_id'), name='notification_condition_unique')],
            },
        ),
        migrations.CreateModel(
            name='NotificationPreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('STOCK', 'Estoque mínimo'), ('MARGIN', 'Margem de venda'), ('DUE', 'Contas a pagar e receber'), ('BACKUP', 'Backup')], max_length=10)),
                ('enabled', models.BooleanField(default=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('user', 'kind'), name='notification_preference_unique')],
            },
        ),
        migrations.CreateModel(
            name='NotificationRead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('revision', models.PositiveIntegerField()),
                ('read_at', models.DateTimeField(auto_now=True)),
                ('notification', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='notifications.notification')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('notification', 'user'), name='notification_read_unique')],
            },
        ),
    ]
